ARG TARGETPLATFORM=linux/amd64
FROM --platform=$TARGETPLATFORM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV CMAKE_VERSION="v3.28.5"
ENV CMAKE_TAR="cmake-3.28.5-linux-x86_64.tar.gz"
ENV CCACHE_VERSION="v4.9.1"
ENV CCACHE_DIR="ccache-4.9.1-linux-x86_64"
ENV CCACHE_TAR="ccache-4.9.1-linux-x86_64.tar.xz"

# Base tools
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates apt-transport-https software-properties-common lsb-release \
       wget curl git make gfortran gcc g++ swig xz-utils \
       gcc-12 g++-12 \
       python3.11 python3.11-dev python3.11-distutils python3-setuptools \
       libopenblas-openmp-dev libcurl4-openssl-dev libaio-dev libevent-dev \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 120 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 311 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3 \
    && pip3 install wheel \
    && rm -rf /var/lib/apt/lists/*

# CMake + ccache
RUN cd /tmp \
    && wget -q https://github.com/Kitware/CMake/releases/download/${CMAKE_VERSION}/${CMAKE_TAR} \
    && tar --strip-components=1 -xz -C /usr/local -f ${CMAKE_TAR} \
    && rm -f ${CMAKE_TAR} \
    && wget -q https://github.com/ccache/ccache/releases/download/${CCACHE_VERSION}/${CCACHE_TAR} \
    && tar -xf ${CCACHE_TAR} \
    && cp ${CCACHE_DIR}/ccache /usr/local/bin \
    && rm -rf ${CCACHE_TAR} ${CCACHE_DIR}

# Conan 1 (matching CI) + JFrog remote
RUN pip3 install "conan==1.61.0" \
    && conan remote add default-conan-local https://milvus01.jfrog.io/artifactory/api/conan/default-conan-local

WORKDIR /workspace
